WebApp/BigData/BigData/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('createjob/', include('createjob.urls')),
]

WebApp/BigData/createjob/urls.py
from django.urls import path
from . import views

app_name = "createjob"
urlpatterns =[
    path('', views.index, name = 'index'),
    path('submit', views.submit, name ='submit')
]

WebApp/BigData/homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"
urlpatterns =[
    path('', views.index, name = 'index')
]

WebApp/BigData/createjob/models.py
from django.db import models

# Create your models here.

WebApp/BigData/homepage/models.py
from django.db import models

# Create your models here.

WebApp/BigData/createjob/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt
import requests

@csrf_exempt
def index(request):
    return render(request, "createjob/index.html")
@csrf_exempt
def submit(request):
    if request.method == 'POST':
        subreddit = request.POST.get('subreddit')
        topic = request.POST.get('topic')
        response = requests.post("https://bdfinalproject.azurewebsites.net/api/jobs?subreddit=%s&topic=%s&min_messages=1000" % (subreddit, topic))
    return redirect("homepage:index")
# Create your views here.

WebApp/BigData/homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests

def index(request):
    response = requests.get('https://bdfinalproject.azurewebsites.net/api/jobs')
    jobdata = response.json()



    return render(request, "homepage/index.html", {
        'joblist' : jobdata["jobList"]
    })
# Create your views here.

WebApp/BigData/templates/createjob/index.html
{% load static %}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Bootstrap core CSS -->
<link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'homepage.css' %}" rel = "stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>


<div class="row">
  <div class="col-md-12">
    <div class="box box-aqua">
      <div class="box-header ui-sortable-handle" style="cursor: move;">
        <i class="ion ion-clipboard"></i>
        <h3 class="box-title">Reddit Jobs</h3>
      </div>

<form action ="{% url 'createjob:submit' %}", method = "post">
  {% csrf_token %}
  <div class="form-group">
    <label for="topic1">Topic</label>
    <input  name="topic" class="form-control" id="topic1" aria-describedby="emailHelp" placeholder="Enter Topic">
  </div>
  <div class="form-group">
    <label for="subreddit1">Subreddit</label>
    <input name="subreddit"  class="form-control" id="subreddit1" placeholder="Enter Subreddit">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

    </div>
  </div>

</div>

WebApp/BigData/templates/homepage/index.html
{% load static %}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Bootstrap core CSS -->
<link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'homepage.css' %}" rel = "stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>


<div class="row">
  <div class="col-md-12">
    <div class="box box-aqua">
      <div class="box-header ui-sortable-handle" style="cursor: move;">
        <i class="ion ion-clipboard"></i>
        <h3 class="box-title">Reddit Jobs</h3>
      </div>

      <div class="box-body">
        <div class="card-columns grid-container">
          {% for job in joblist %}
          <div class="card" style="width: 18rem;">
             <div class="card-body">
                <h5 class="card-title">{{ job.id }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">Topic : {{ job.topic }}</h6>
                <p class="card-text">Created time: {{ job.created_datetime }}</p>
                <p class="card-text">Job Status: {{ job.job_status }}</p>
                <a href="#" class="card-link">Subreddit: {{job.subreddit}}</a>
                <a href="#" class="card-link">Result: {{job.result}}</a>
              </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="box-footer clearfix no-border">
      <a type="button" href = "{% url 'createjob:index'%}" class="btn btn-default pull-right"><i class="fa fa-plus"></i> Add Job</a>
      </div>
    </div>
  </div>

</div>